apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: approve-carrier-allchannel-supplychain1
  namespace: carrier-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: approve-carrier-allchannel-supplychain1
  chart:
    git: git@github.com:abevers/blockchain-automation-framework.git
    ref: demo/hl-meetup
    path: platforms/hyperledger-fabric/charts/approve_chaincode
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.hf.demo.aws.blockchaincloudpoc.com:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.0
      name: supplychain
      version: 1
      commitarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: allchannel
