apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: join-allchannel-manufacturer-peer0
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: join-allchannel-manufacturer-peer0
  chart:
    git: git@github.com:abevers/blockchain-automation-framework.git
    ref: demo/hl-meetup
    path: platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: manufacturer-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.manufacturer-net.hf.demo.aws.blockchaincloudpoc.com:8443
      localmspid: manufacturerMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      authpath: manufacturer-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/manufacturer-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/manufacturer-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.hf.demo.aws.blockchaincloudpoc.com:8443

