apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: manufacturermanufacturerconstellation
  namespace: manufacturer-quo
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: manufacturermanufacturerconstellation
  chart:
    git: git@github.com:abevers/blockchain-automation-framework.git
    ref: feature/helm3
    path: platforms/quorum/charts/node_constellation
  values:
    replicaCount: 1
    metadata:
      namespace: manufacturer-quo
      labels: 
    images:
      node: quorumengineering/quorum:2.5.0
      alpineutils: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
      constellation: quorumengineering/constellation:0.3.2
    node:
      name: manufacturer
      status: default
      consensus: ibft
      subject: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH
      mountPath: /etc/quorum/qdata
      imagepullsecret: regcred
      keystore: keystore_1
      servicetype: ClusterIP
      lock: true/false
      ports:
        rpc: 8546
        raft: 50401
        constellation: 8443
        quorum: 21000
    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:8200
      secretprefix: secret/manufacturer-quo/crypto/manufacturer
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: transaction
      role: vault-role
      authpath: quorummanufacturer
    genesis: ewogICAgImNvbmZpZyI6IHsKICAgICAgICAiY2hhaW5JZCI6IDEwLAogICAgICAgICJob21lc3RlYWRCbG9jayI6IDAsCiAgICAgICAgImVpcDE1MEJsb2NrIjogMCwKICAgICAgICAiZWlwMTUwSGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgICAgICJlaXAxNTVCbG9jayI6IDAsCiAgICAgICAgImVpcDE1OEJsb2NrIjogMCwKICAgICAgICAiYnl6YW50aXVtQmxvY2siOiAxLAogICAgICAgICJjb25zdGFudGlub3BsZUJsb2NrIjogMCwKICAgICAgICAiaXN0YW5idWwiOiB7CiAgICAgICAgICAgICJlcG9jaCI6IDMwMDAwLAogICAgICAgICAgICAicG9saWN5IjogMCwKICAgICAgICAgICAgImNlaWwyTmJ5M0Jsb2NrIjogMAogICAgICAgIH0sCiAgICAgICAgInR4blNpemVMaW1pdCI6IDEyOCwKICAgICAgICAibWF4Q29kZVNpemUiOiAxMjgsCiAgICAgICAgImlzUXVvcnVtIjogdHJ1ZQogICAgfSwKICAgICJub25jZSI6ICIweDAiLAogICAgInRpbWVzdGFtcCI6ICIweDVmMDMyY2JjIiwKICAgICJleHRyYURhdGEiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjg5YWY4NTQ5NDU4ODMwY2NiNWZkOTQwZDk5YTA2NTZiNTZlYWRlMjdiZDZjYjkxNTY5NDk1YzA0ZWYwOGYxZjYzMDMzNWExYjE3NzRiZDdlNTBjYTE3ZmIxYjA5NGIwZTMwZWQxZWJhMzkyOGEyMTIxZWMyNmRhYzJkY2FmMjE0OGY5M2U5NDA0OWE5YTFkOWUwOGFlZWY5OTQ5NTFkMDljZWVjY2JhZWI5NDQ2YzBiODQxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGMwIiwKICAgICJnYXNMaW1pdCI6ICIweGUwMDAwMDAwIiwKICAgICJkaWZmaWN1bHR5IjogIjB4MSIsCiAgICAibWl4SGFzaCI6ICIweDYzNzQ2OTYzNjE2YzIwNjI3OTdhNjE2ZTc0Njk2ZTY1MjA2NjYxNzU2Yzc0MjA3NDZmNmM2NTcyNjE2ZTYzNjUiLAogICAgImNvaW5iYXNlIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsCiAgICAiYWxsb2MiOiB7CiAgICAgICAgIjA0OWE5YTFkOWUwOGFlZWY5OTQ5NTFkMDljZWVjY2JhZWI5NDQ2YzAiOiB7CiAgICAgICAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgICAgIH0sCiAgICAgICAgIjU4ODMwY2NiNWZkOTQwZDk5YTA2NTZiNTZlYWRlMjdiZDZjYjkxNTYiOiB7CiAgICAgICAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgICAgIH0sCiAgICAgICAgIjk1YzA0ZWYwOGYxZjYzMDMzNWExYjE3NzRiZDdlNTBjYTE3ZmIxYjAiOiB7CiAgICAgICAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgICAgIH0sCiAgICAgICAgImIwZTMwZWQxZWJhMzkyOGEyMTIxZWMyNmRhYzJkY2FmMjE0OGY5M2UiOiB7CiAgICAgICAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgICAgIH0KICAgIH0sCiAgICAibnVtYmVyIjogIjB4MCIsCiAgICAiZ2FzVXNlZCI6ICIweDAiLAogICAgInBhcmVudEhhc2giOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgp9
    staticnodes: 
      [
    "enode://207fd6d7bfc4ac7edd8eeea882495a895458788a9da6379bbf4742278edc2f479d0c22f8dcc2a65feb6336fec547ddbfba6069f4864488d1a3e9d6ade222bce3@carrier.test.quorum.blockchaincloudpoc.com:15010?discport=0",
    "enode://21225f64c54f1aa4e9c4b0d5abbdd38e0494fa82776805513f83b80239ece1dc07eeaec38bcf5cec9541f8e3c2d494031140f2213f8df2a898ddf35114845d08@manufacturer.test.quorum.blockchaincloudpoc.com:15020?discport=0",
    "enode://1a62cac60e0758d3096e18bc7a824470d9cb2fbcdc1db4cf3273b67eda33b9773fc7fc4545b271453f60a8c5f33741e8ca64114675d3f2b6411045ba78fb90f1@store.test.quorum.blockchaincloudpoc.com:15030?discport=0",
    "enode://b0879942f8b32020ebdc95315c7daf0bd8a7843d5046f97e9eca8dc0bb2a27ad1dba94cc5259a800cc09e0471cdaf7582c9fa7ea013ebf36f6f95100dc92a9d2@warehouse.test.quorum.blockchaincloudpoc.com:15040?discport=0"
]
    constellation:
      url: https://manufacturer.test.quorum.blockchaincloudpoc.com:8443/
      storage: "bdb:/etc/quorum/qdata/database"
      tls: "strict"
      othernodes: ['https://carrier.test.quorum.blockchaincloudpoc.com:8443', 'https://manufacturer.test.quorum.blockchaincloudpoc.com:8443', 'https://store.test.quorum.blockchaincloudpoc.com:8443', 'https://warehouse.test.quorum.blockchaincloudpoc.com:8443']
      trust: "tofu"
    proxy:
      provider: "ambassador"
      external_url_suffix: test.quorum.blockchaincloudpoc.com
      rpcport: 15021
      quorumport: 15020
      portConst: 8443
      portRaft: 15023
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
