apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-carrierab-allchannel
  namespace: carrierab-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-carrierab-allchannel
  chart:
    git: git@github.com:abevers/blockchain-automation-framework.git
    ref: fabric-comp-test
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: carrierab-net
      network:
        version 1.4.0
      images:
        fabrictools: hyperledger/fabric-tools:1.4.0
        alpineutils: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrierab-net:7051
      localmspid: carrierabMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: carrierab-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrierab-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrierab-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer9.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    channeltx: |-
      CtACChgKFggCGgYIjc+Y/gUiCmFsbGNoYW5uZWwSswIKsAIKCmFsbGNoYW5uZWwSMxIhCgtBcHBs
      aWNhdGlvbhISEhAKDGNhcnJpZXJhYk1TUBIAGg4KCkNvbnNvcnRpdW0SABrsARLAAQoLQXBwbGlj
      YXRpb24SsAEIARIQCgxjYXJyaWVyYWJNU1ASABomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRf
      MhIAGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5z
      EhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZB
      ZG1pbnMqBkFkbWlucxonCgpDb25zb3J0aXVtEhkSFwoVU3VwcGx5Q2hhaW5Db25zb3J0aXVt