apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-carrierab
  namespace: carrierab-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-carrierab
  chart:
    git: git@github.com:abevers/blockchain-automation-framework.git
    ref: fabric-comp-test
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: carrierab-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.carrierab-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
      localmspid: carrierabMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: carrierab-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrierab-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrierab-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer9.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    anchorstx: |-
      Cs8CChAKDggCIgphbGxjaGFubmVsEroCCrcCCgphbGxjaGFubmVsElwSWgoLQXBwbGljYXRpb24S
      SwgBEj8KDGNhcnJpZXJhYk1TUBIvGgcKA01TUBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJzEgAi
      CgoGQWRtaW5zEgAqBkFkbWlucxrKARLHAQoLQXBwbGljYXRpb24StwEIARKqAQoMY2FycmllcmFi
      TVNQEpkBCAEaBwoDTVNQEgAaXgoLQW5jaG9yUGVlcnMSTxJFCkMKPnBlZXIwLmNhcnJpZXJhYi1u
      ZXQuaGYuZGV2Mi5hd3MuYmxvY2tjaGFpbmNsb3VkcG9jLWRldmVsb3AuY29tEPtBGgZBZG1pbnMi
      CgoGQWRtaW5zEgAiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSACoGQWRtaW5zKgZBZG1pbnM=

