apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: commit-carrierab-allchannel-supplychain1
  namespace: carrierab-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: commit-carrierab-allchannel-supplychain1
  chart:
    git: git@github.com:abevers/blockchain-automation-framework.git
    ref: feature/1088-couchdb-image
    path: platforms/hyperledger-fabric/charts/commit_chaincode
  values:
    metadata:
      namespace: carrierab-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrierab-net:7051
      localmspid: carrierabMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: carrierab-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrierab-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrierab-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer9.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.0
      name: supplychain
      version: 1
      commitarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: allchannel
    endorsers:
      creator: carrierab-net
      name:  carrierab  
      corepeeraddress:  peer0.carrierab-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443 
