apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: notaryab
  namespace: cenmab-ent
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: notaryab
  chart:
    git: git@github.com:abevers/blockchain-automation-framework.git
    ref: feature/977-test
    path: platforms/corda-ent/charts/notary
  values:
    nodeName: notaryab
    metadata:
      namespace: cenmab-ent
    image:
      initContainerName: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
      nodeContainerName: adopblockchaincloud0502.azurecr.io/corda/enterprise-notary:1.2-zulu-openjdk8u242
      imagePullSecret: regcred
      pullPolicy: Always
      privateCertificate: true
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      certSecretPrefix: secret/cenmab
      serviceAccountName: vault-auth
      role: vault-role
      authPath: cordaentcenmab
      retries: 30
      retryInterval: 10
    service:
      p2pPort: 10002
      sshdPort: 2222
      rpc:
        address: "0.0.0.0"
        addressPort: 10003
        admin:
          address: "localhost"
          addressPort: 10770
        standAloneBroker: false
        useSSL: false
        users:
          username: notary
          password: notaryP
    networkServices:
      idmanName: idmanab
      doormanURL: https://idmanab.rc.dev2.aws.blockchaincloudpoc-develop.com:8443
      idmanDomain: idmanab.rc.dev2.aws.blockchaincloudpoc-develop.com
      networkmapName: networkmapab
      networkMapURL: https://networkmapab.rc.dev2.aws.blockchaincloudpoc-develop.com:8443
      networkMapDomain: networkmapab.rc.dev2.aws.blockchaincloudpoc-develop.com
    dataSourceProperties:
      dataSource:
        password: "notaryab-db-password"
        url: "jdbc:h2:tcp://notaryabdb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
        user: "notaryab-db-user"
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dbUrl: "notaryabdb"
      dbPort: 9101
    nodeConf:
      legalName: O=Notary,OU=Notary1,L=London,C=GB
      emailAddress: dev@baf.com
      notaryPublicIP: notaryab.rc.dev2.aws.blockchaincloudpoc-develop.com
      devMode: false
      notary:
        validating: True
      p2p:
        url: notaryab.cenmab-ent
      ambassador:
        p2pPort: 15083
        external_url_suffix: rc.dev2.aws.blockchaincloudpoc-develop.com
        p2pAddress: notaryab.rc.dev2.aws.blockchaincloudpoc-develop.com:15083
      jarPath: bin
      configPath: etc
      cordaJar:
        memorySize: 1524
        unit: M
      volume:
        baseDir: /opt/corda/base
      pod:
        resources:
          limits: 2056M
          requests: 2056M
      storage:
        name: cordaentsc
        memory: 512Mi
      replicas: 1
    healthCheckNodePort: 0
    sleepTimeAfterError: 60
    sleepTime: 10
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
